-- MySQL Script generated by MySQL Workbench
-- Mon May 28 11:05:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`test_configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test_configuration` (
  `ID` INT NOT NULL COMMENT 'Identificador do teste\n',
  `Name` VARCHAR(45) NULL COMMENT 'Nome do teste',
  `n_threads` INT NOT NULL COMMENT 'Numero de threads',
  `ramp_up` INT NOT NULL COMMENT 'Inicio Threads (ramp-up) (s)',
  `runs` INT NOT NULL COMMENT 'Loop count',
  `n_clients` INT NOT NULL COMMENT 'Numero de clientes',
  `duration` INT NOT NULL COMMENT 'Duração (s)',
  `protocol` VARCHAR(45) NOT NULL COMMENT 'Protocolo (HTTP / HTTPS)',
  `server_name` VARCHAR(45) NOT NULL COMMENT 'Endereço Servidor/IP',
  `server_port` INT NOT NULL COMMENT 'Porto do servidor',
  `test_file` BLOB NULL COMMENT 'Nome do ficheiro de testes',
  `date_conf` DATE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
