on:
  port: 8886
  address: 0.0.0.0

rapidoid:
  port: 8886
  address: 0.0.0.0

http:
  serverName: myserver

gui:
  domain: ''
  brand: Distmeter
  search: true
  navbar: true
  fluid: true
  cdn: auto # in DEV mode is false, in PRODUCTION is true
  menu:
    Home: /
    AddTest: /addtest.html
    About: /about.html

log:
  level: debug

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/distmeter_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
  username: distmeter
  password: lei_distmeter_pass
  port: 3306
  options: logger=Slf4JLogger

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect9DialectQL5Dialect
  connection:
      driver_class: com.mysql.jdbc.Driver
      username: distmeter
      password: lei_distmeter_pass
      url: jdbc:mysql://localhost:3306/distmeter_db?verifyServerCertificate=false&useSSL=false&requireSSL=false
